### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by ampolenberg** [uiowa-mgb/uiowa-thesis#4]
From the guidelines:

> Line spacing may be either 1.5 or double-spaced. Line spacing should be consistent throughout.

Currently, the class file allows for single-spaced lines, which is non-compliant. 

There are also multiple options(?) available for double-spaced lines (all of which are compliant, albeit strange). This can probably be condensed and/or fixed to make more sense.

**Comment by erooke** [comment]
Closed cause we ditched the old cls file and rewrote from scratch
