### ISSUE TITLE
Change in title page

### ISSUE THREAD

**Issue by jared3831** [uiowa-mgb/uiowa-thesis#5]
I just got preliminary feedback from the graduate college using this template and in the thesis.tex file it should be:
\concentration{Applied Mathematics and Computational Sciences}
not 
\concentration{Applied Mathematics \& Computational Sciences}

apparently the \appendixpage isn't required.
"The Appendices heading on p. xx isn't necessary. You can treat the Appendix headings just like the chapter headings, and so they don't need the extra heading. If, though, this is part of the LaTex template you're using, then it can stay)"

**Comment by erooke** [comment]
Thank you for letting us know. I have updated the example thesis to correct the concentration. I have also removed the `\appendixpage` from the example. I personally like it but the few people I have checked with seem to not be a fan.
